//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starkk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogYazi
    {
        public int Id { get; set; }
        public int RefBlogKategoriId { get; set; }
        public string Baslik { get; set; }
        public string Yazi { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime Tarih { get; set; }
        public string Yazar { get; set; }
        public string Seo { get; set; }
    
        public virtual BlogKategori BlogKategori { get; set; }
    }
}
