//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starkk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class ResimUrun
    {
        public int Id { get; set; }
        public int RefUrunId { get; set; }
        public byte[] Resim { get; set; }
    
        public virtual Urunler Urunler { get; set; }


        [NotMapped]
        public IEnumerable<HttpPostedFileBase> ResimFile { get; set; }
    }
}
