//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public Nullable<double> Fiyatı { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Adet { get; set; }
    }
}
